name = "MultivariateMoments"
uuid = "f4abf1af-0426-5881-a0da-e2f168889b5e"
repo = "https://github.com/JuliaAlgebra/MultivariateMoments.jl.git"
version = "0.2.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
RowEchelon = "af85af4c-bcd5-5d23-b03a-a909639aa875"
SemialgebraicSets = "8e049039-38e8-557d-ae3a-bc521ccf6204"

[compat]
MultivariatePolynomials = "≥ 0.1.0"
SemialgebraicSets = "≥ 0.0.1"
julia = "1"

[extras]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DynamicPolynomials", "Test"]
